FROM alpine AS Dev

WORKDIR /root

RUN apk add --no-cache build-base libffi-dev openssl-dev python3 python3-dev py3-pip && \
    wget "https://raw.githubusercontent.com/ShadowUser17/PromTools/main/prometheus/requirements.txt" && \
    python3 -m venv --upgrade-deps env && \
    ./env/bin/pip3 install --no-cache -r requirements.txt && \
    wget "https://raw.githubusercontent.com/ShadowUser17/PromTools/main/prometheus/health_check_exporter.py" -O "env/exporter.py"


FROM python:alpine AS Prod

WORKDIR /opt

RUN ln -s /usr/local/bin/python3 /usr/bin/python3

COPY --from=Dev /root/env ./env

EXPOSE 9097/tcp

ENTRYPOINT ["env/bin/python3", "env/exporter.py", "-l", "0.0.0.0", "-p", "9097"]
