FROM alpine AS Dev

WORKDIR /root

COPY ./requirements.txt ./

RUN apk add --no-cache build-base libffi-dev openssl-dev python3 python3-dev py3-pip && \
    python3 -m venv --upgrade-deps env && \
    ./env/bin/pip3 install --no-cache -r ./requirements.txt

FROM python:alpine AS Prod

WORKDIR /opt

COPY --from=Dev /root/env ./env
COPY ./hc_exporter.py ./env/exporter.py

RUN ln -s /usr/local/bin/python3 /usr/bin/python3

EXPOSE 9097/tcp

ENTRYPOINT ["./env/bin/python3", "./env/exporter.py", "-l", "0.0.0.0", "-p", "9097"]
